/*
 * This file is generated by jOOQ.
 */
package jooqdata;


import jooqdata.tables.Customer;
import jooqdata.tables.Lot;
import jooqdata.tables.records.CustomerRecord;
import jooqdata.tables.records.LotRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * purchase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerRecord> CUSTOMER_PKEY = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("customer_pkey"), new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE }, true);
    public static final UniqueKey<LotRecord> LOT_PKEY = Internal.createUniqueKey(Lot.LOT, DSL.name("lot_pkey"), new TableField[] { Lot.LOT.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CustomerRecord, CustomerRecord> CUSTOMER__CUSTOMER_CUSTOMER_CODE_MAIN_FKEY = Internal.createForeignKey(Customer.CUSTOMER, DSL.name("customer_customer_code_main_fkey"), new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE_MAIN }, Keys.CUSTOMER_PKEY, new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE }, true);
    public static final ForeignKey<LotRecord, CustomerRecord> LOT__LOT_CUSTOMER_CODE_FKEY = Internal.createForeignKey(Lot.LOT, DSL.name("lot_customer_code_fkey"), new TableField[] { Lot.LOT.CUSTOMER_CODE }, Keys.CUSTOMER_PKEY, new TableField[] { Customer.CUSTOMER.CUSTOMER_CODE }, true);
}
